version: '3.7'

services:
  app:
    restart: always
    build:
      context: '.'
    environment:
      NUM_PROCS: 8
      UPDATE_INTERVAL: 30
    ports:
      - '127.0.0.1:5000:5000'
    volumes:
      - './:/app'
